#!/bin/bash

## This is used to see if Installed O365 is Mojave compatible seeing as jamf broke patch management

# variables

App1="Microsoft Outlook.app"
App2="Microsoft Word.app"
App3="Microsoft Excel.app"
App4="Microsoft PowerPoint.app"


# clearing variables
App1_Compatible=""
App2_Compatible=""
App3_Compatible=""
App4_Compatible=""


# Minimum version 16.17 is Mojave compatible
MinimumVersion="1617"

# Set result if O365 apps are not installed because the don’t exist 
if [ ! -e /Applications/"$App1" ] && [ ! -e /Applications/"$App2" ] && [ ! -e /Applications/"$App3" ] && [ ! -e /Applications/"$App4" ]; then
echo "<result>Not Installed</result>"
fi

if [ -e /Applications/"$App1" ]; then
	InstalledO365_App1=$(defaults read /Applications/"$App1"/Contents/Info.plist CFBundleShortVersionString | tr -d ".")
fi

 
# App2 Check
if [ -e /Applications/"$App2" ]; then
	InstalledO365_App2=$(defaults read /Applications/"$App2"/Contents/Info.plist CFBundleShortVersionString | tr -d ".")
fi


# App3 Check
if [ -e /Applications/"$App3" ]; then
	InstalledO365_App3=$(defaults read /Applications/"$App3"/Contents/Info.plist CFBundleShortVersionString | tr -d ".")
fi


# App 4 Check
if [ -e /Applications/"$App4" ]; then
	InstalledO365_App4=$(defaults read /Applications/"$App4"/Contents/Info.plist CFBundleShortVersionString | tr -d ".")
fi





# Final result, if none of the apps came back not compatible then we are good
if [[ "$InstalledO365_App1" -ge "$MinimumVersion" ]] && [[ "$InstalledO365_App2" -ge "$MinimumVersion" ]] && [[ "$InstalledO365_App3" -ge "$MinimumVersion" ]] && [[ "$InstalledO365_App4" -ge "$MinimumVersion" ]]; then
echo "<result>Compatible</result>"
else
echo "<result>Not Compatible</result>"
fi

exit 0
