#!/bin/bash

###################################################################################################################################
# BUILD 3
#
# TIM KIMPTON
#
# This script is used to migrate machine from one Jamf Server to Another
# This does the following
# 1.Checks for a working internet connection
# 2. Check both of the jss server healthcheck pages to make sure the db connections are ok (defined in $6 & $7 of the policy)
# 3.The mdm profile is removed
# 4.The machine is enrolled using the invitation (defined in $8)
# 5.If the machine is 10.13+ a dialog is shown for the UAMDM
#
####################################################################################################################################


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# USER VARIABLES
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

GOOGLE="8.8.8.8"
TEMPFILE1=/private/tmp/CheckJSSConnection1.txt
TEMPFILE2=/private/tmp/CheckJSSConnection1.txt

CURRENT_JAMF_URL=$6   #https://xxx.jamfcloud.com
NEW_JAMF_URL=$7        #https://xxx.jamfcloud.com
INVITATION=$8 

TMP_IMAGE="/tmp/uamdm_ss.png"
CocoaDialog="/usr/local/bin/cocoaDialog.app/Contents/MacOS/cocoaDialog"
TITLE="ServiceNow IT"
HEADER="User Approve MDM"
REQ_JAMF=$(defaults read /Library/Preferences/com.jamfsoftware.jamf.plist jss_url)


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# SYSTEM VARIABLES
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

osMinorVersion=$( /usr/bin/sw_vers -productVersion | /usr/bin/cut -d. -f2 )
timestamp=$( /bin/date '+%Y-%m-%d-%H-%M-%S' )
mySerial=$( system_profiler SPHardwareDataType | grep Serial |  awk '{print $NF}' )


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# FUNCTIONS
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# create the temporary logo for the UAMDM prompt
function tmp_Logo(){

if [ -e $TMP_IMAGE ]; then
        rm $TMP_IMAGE
fi

cat << EOF | base64 -D > "$TMP_IMAGE"
iVBORw0KGgoAAAANSUhEUgAAAIQAAACACAYAAADK1cGxAAAMSGlDQ1BJQ0MgUHJvZmlsZQAASImVVwdUU8kanltSSWiBCEgJvYlSBAJICaFFEJAq2AhJIKHEmBBE7CzLKrh2EQF1RVdFXHQtgKwVe1
kUe39YUFHWxYINlTcpsK573nvn/efMne/+88/3l0zmzgCgV8uXyfJQfQDypQXyhMhQ1oS0dBbpASACKtADbODCFyhknPj4GABlsP+7vL0GEFV/2U3F9c/x/yoGQpFCAAASD3GmUCHIh3gvAHipQCYv
AIDIhnrbGQUyFZ4EsZEcBgixTIWzNbhUhTM1uEptk5TAhXgHAGQany/PBkC3BepZhYJsyKN7A2J3qVAiBUCPDHGQQMwXQhwF8Yj8/GkqDO2AU+ZXPNl/48wc4uTzs4ewJhe1kMMkClkef+b/WY7/Lf
l5ykEfDrDRxPKoBFXOsG43cqdFqzAN4h5pZmwcxIYQv5cI1fYQo1SxMipZY4+aCxRcWDPAhNhdyA+Lhtgc4ghpXmyMVp+ZJYngQQxXCFokKeAlaecuFCnCE7WctfJpCXGDOEvO5WjnNvLlar8q++PK
3GSOlv+GWMQb5H9TLE5K1cSMUQslKbEQ60LMVOQmRmtsMLtiMTd20EauTFDFbwexv0gaGarhx6ZkySMStPbyfMVgvthCsYQXq8XVBeKkKC3PDgFfHb8JxC0iKSd5kEekmBAzmItQFBauyR27KJIma/
PFOmUFoQnaua9kefFae5wqyotU6W0gNlcUJmrn4kEFcEFq+PFYWUF8kiZOPDOHPzZeEw9eBGIAF4QBFlDClgmmgRwgae9p7oFvmpEIwAdykA1EwE2rGZyRqh6RwmciKAZ/QCQCiqF5oepRESiE+s9D
Ws3TDWSpRwvVM3LBY4jzQTTIg+9K9SzpkLcU8AhqJP/wLoCx5sGmGvunjgM1MVqNcpCXpTdoSQwnhhGjiBFEZ9wMD8ID8Bj4DIHNE2fjfoPR/mVPeEzoIDwgXCV0Em5OlZTIv8mHBcaBTughQptz5t
c54w6Q1RsPxQMhP+TGmbgZcMNHQ08cPBj69oZarjZyVfbfcv8th6+qrrWjuFNQyjBKCMXp25m6LrreQyyqmn5dIU2smUN15Q6NfOuf+1WlhbCP/tYSW4jtwU5hR7Ez2AGsGbCww1gLdh47qMJDq+iR
ehUNektQx5MLeST/8MfX+lRVUuHe4N7t/kkzViAqUu2PgDtNNlMuyRYXsDhw5xexeFLByBEsT3cPuGurviOabeo1U/19QJhn/9KVZAAQaDUwMHDgL10M3Nf2DQeA+udfOicGAPSTAJwuESjlhRodrn
oQ1N8nI2AKLIEtcIL5eAIfEABCQDgYC+JAEkgDU2CVxXA9y8EMMBssAGWgAiwDq0E12AA2gW3gF7AbNIMD4Cg4Cc6Bi+AquA1XTxd4DnrBW9CPIAgJoSMMxBSxQuwRV8QTYSNBSDgSgyQgaUgGko1I
ESUyG/kOqUBWINXIRqQe+RXZjxxFziAdyE3kPtKNvEI+ohhKQ41QC9QBHYWyUQ4ajSahk9FsdDpajJaiS9AqtA7dgTahR9Fz6FW0E32O9mEA08GYmDXmhrExLhaHpWNZmBybi5VjlVgd1oi1wt/5Mt
aJ9WAfcCLOwFm4G1zBUXgyLsCn43PxxXg1vg1vwo/jl/H7eC/+hUAnmBNcCf4EHmECIZswg1BGqCRsIewjnID/pi7CWyKRyCQ6En3hvzGNmEOcRVxMXEfcSTxC7CA+JPaRSCRTkispkBRH4pMKSGWk
taQdpMOkS6Qu0nuyDtmK7EmOIKeTpeQSciV5O/kQ+RL5Cbmfok+xp/hT4ihCykzKUspmSivlAqWL0k81oDpSA6lJ1BzqAmoVtZF6gnqH+lpHR8dGx09nvI5EZ75Olc4undM693U+0AxpLjQubRJNSV
tC20o7QrtJe02n0x3oIfR0egF9Cb2efox+j/5el6E7UpenK9Sdp1uj26R7SfeFHkXPXo+jN0WvWK9Sb4/eBb0efYq+gz5Xn68/V79Gf7/+df0+A4aBh0GcQb7BYoPtBmcMnhqSDB0Mww2FhqWGmwyP
GT5kYAxbBpchYHzH2Mw4wegyIho5GvGMcowqjH4xajfqNTY0Hm2cYlxkXGN80LiTiTEdmDxmHnMpczfzGvPjMIthnGGiYYuGNQ67NOydyXCTEBORSbnJTpOrJh9NWabhprmmy02bTe+a4WYuZuPNZp
itNzth1jPcaHjAcMHw8uG7h98yR81dzBPMZ5lvMj9v3mdhaRFpIbNYa3HMoseSaRlimWO5yvKQZbcVwyrISmK1yuqw1TOWMYvDymNVsY6zeq3NraOsldYbrdut+20cbZJtSmx22ty1pdqybbNsV9m2
2fbaWdmNs5tt12B3y55iz7YX26+xP2X/zsHRIdXhB4dmh6eOJo48x2LHBsc7TnSnYKfpTnVOV5yJzmznXOd1zhddUBdvF7FLjcsFV9TVx1Xius61YwRhhN8I6Yi6EdfdaG4ct0K3Brf7I5kjY0aWjG
we+WKU3aj0UctHnRr1xd3bPc99s/ttD0OPsR4lHq0erzxdPAWeNZ5XvOheEV7zvFq8Xo52HS0avX70DW+G9zjvH7zbvD/7+PrIfRp9un3tfDN8a32vs43Y8ezF7NN+BL9Qv3l+B/w++Pv4F/jv9v8z
wC0gN2B7wNMxjmNEYzaPeRhoE8gP3BjYGcQKygj6Kagz2DqYH1wX/CDENkQYsiXkCceZk8PZwXkR6h4qD90X+o7rz53DPRKGhUWGlYe1hxuGJ4dXh9+LsInIjmiI6I30jpwVeSSKEBUdtTzqOs+CJ+
DV83rH+o6dM/Z4NC06Mbo6+kGMS4w8pnUcOm7suJXj7sTax0pjm+NAHC9uZdzdeMf46fG/jSeOjx9fM/5xgkfC7IRTiYzEqYnbE98mhSYtTbqd7JSsTG5L0UuZlFKf8i41LHVFaueEURPmTDiXZpYm
SWtJJ6WnpG9J75sYPnH1xK5J3pPKJl2b7Di5aPKZKWZT8qYcnKo3lT91TwYhIzVje8Ynfhy/jt+XycuszewVcAVrBM+FIcJVwm5RoGiF6ElWYNaKrKfZgdkrs7vFweJKcY+EK6mWvMyJytmQ8y43Ln
dr7kBeat7OfHJ+Rv5+qaE0V3p8muW0omkdMldZmaxzuv/01dN75dHyLQpEMVnRUmAED+znlU7K75X3C4MKawrfz0iZsafIoEhadH6my8xFM58URxT/PAufJZjVNtt69oLZ9+dw5myci8zNnNs2z3Ze
6byu+ZHzty2gLshd8HuJe8mKkjffpX7XWmpROr/04feR3zeU6ZbJy67/EPDDhoX4QsnC9kVei9Yu+lIuLD9b4V5RWfFpsWDx2R89fqz6cWBJ1pL2pT5L1y8jLpMuu7Y8ePm2FQYrilc8XDluZdMq1q
ryVW9WT119pnJ05YY11DXKNZ1VMVUta+3WLlv7qVpcfbUmtGZnrXntotp364TrLq0PWd+4wWJDxYaPP0l+urExcmNTnUNd5SbipsJNjzenbD71M/vn+i1mWyq2fN4q3dq5LWHb8Xrf+vrt5tuXNqAN
yobuHZN2XPwl7JeWRrfGjTuZOyt2gV3KXc9+zfj12u7o3W172Hsa99rvrd3H2FfehDTNbOptFjd3tqS1dOwfu7+tNaB1328jf9t6wPpAzUHjg0sPUQ+VHho4XHy474jsSM/R7KMP26a23T424diV4+
OPt5+IPnH6ZMTJY6c4pw6fDjx94Iz/mf1n2Webz/mcazrvfX7f796/72v3aW+64Huh5aLfxdaOMR2HLgVfOno57PLJK7wr567GXu24lnztxvVJ1ztvCG88vZl38+Wtwlv9t+ffIdwpv6t/t/Ke+b26
fzn/a2enT+fB+2H3zz9IfHD7oeDh80eKR5+6Sh/TH1c+sXpS/9Tz6YHuiO6LzyY+63oue97fU/aHwR+1L5xe7P0z5M/zvRN6u17KXw68Wvza9PXWN6PftPXF9917m/+2/135e9P32z6wP5z6mPrxSf
+MT6RPVZ+dP7d+if5yZyB/YEDGl/PVRwEMNjQrC4BXW+E5IQ0AxkV4fpioueepBdHcTdUI/CesuQuqxQeARtipjuvcIwDsgs0BNjp8Vx3Vk0IA6uU11LSiyPLy1HDR4I2H8H5g4LUFAKRWAD7LBwb6
1w0MfN4Mg70JwJHpmvulSojwbvCTmuMSs2g++Eb+DSk1fp91Mz8NAAAACXBIWXMAABYlAAAWJQFJUiTwAAABnWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG
9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAg
ICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyI+CiAgICAgICAgIDxleGlmOlBpeGVsWERpbW
Vuc2lvbj4xMzI8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MTI4PC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRp
b24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CqaCP4MAAAAcaURPVAAAAAIAAAAAAAAAQAAAACgAAABAAAAAQAAAH0vMfh8pAAAfF0lEQVR4Aezdx68dxbYG8DYm55yDweScGTIi6b7ZfRNEFi
BA/DmAECDyBSYwYYCESBIMyDlnk3M0GYxf/ersb7tOn94n4MMV1nNJdaq7K6z0rVWrurdhyQcffLC6G5XVq1d36qpVq7rff/+9++OPP7o///yz1vRl7Pp23dHAkiVLOnWDDTaodcMNN+w22mijbunS
pfW5vpQlAQSDMz4QAMQQADxbX9Y9DbQGx30AAhDAASgZUwER44sKv/zyS5V400037dSNN964osmk9WXd1QBnZ9/ffvut2ri1s2gRkFRAJDKIDirUbLnllt3mm29eQeF+fVn3NcC2gPDTTz91P/zwQw
UIMLDvOFLYMgz89ddfq8QiwmabbVYBsckmm9RwIoL8XpD1Z9lK1pd1TwMblK1ho2JXUYDzszVAAIaI4TlbA0WNEEKJTtvCNtts0225xRZ1wNJRZKhJZllEu76sexqQK2xUDK5VVo0CwA8//th99913
1a5bFJvXrUOEgJKVK1fWB7vsvHPdKlYXJCWJ1EJW7tc9lfz/5lgEmJY4lvslxfkFgc8+/7xuHVtttVXNF2uEEEIgZeOyn+y2224VEH+UqAEESj1bFFAARK3Rb7lfX/6BGigGV/xNslgu6r3nwLFhsT
VAfPLJJ91vxdZ2BttGBYRE49tvv+02LCFll1126YSPGN8CroFD/cORVLSY6vB3ffmnaWBkfFGATQFgRoQoY34sW8Znn31WbbrtttvWA0QFxM8//9x98803dY+xZThhtAUQ5A+/lq3FWAnJ999/XxeU
f8yVWwRQWqUfwlpa/esAM9EqiCfgXGVt6Fo7ThA68+V7beiujbw1Vyie73RYc8FiRweETUpCqa+vM3a0ZbDfdtttV8eOAfH111/XSbuWCCGpbMuqAghhxQLGvffee93LL7/cvf/++zWy5EzbzmmvEZ
SnOM0QGHPCk5aSJxVjzVUBL3PbY9KkuZ6HrpZxF0IXLfzi21zKNN8pTDtbQc82rA3P85EXHXPU6Iqs6OVYOIkuOt4b8fS99967O/zww7t99tmn23777auDSweW9pxIUvlpiRDoGQc80wFRJlRA9CKE
bUJ0EF5ee+21Wl999dXuww8/rLnHbIBgcAQZlJCuCYh5QhJkthLDoOGaQaKk2cBkTQpGM1GMUQk9H7rmmysiWsccVSbe9zRjUyLvECDmoku+8AyISuRFcy55gU5yuOeee1ZAHHLIId1BBx1U0wBRwv
bRFg5eAVHkmwGIr776qhpqNxGiAQRzMSIBX3v99e6ee+7pgIGi4rUtkf51KwRhzfGMoIT0bBIojAMe9AMIQPJstnnhwXzV/CjY/IXQlXgpLd2sP9SiR54YF5+e5W1g+ibNDW9xstAlwyQ9WQsNtIyj
26233ro77LDDutNOO607uIBiHKEawgDxyShC7LDDDtMjxBAg4rs1QhRAPPvss91tt91WI4R9irdhGPKHCiZTIyivU8yJEAQZKuYYpx8gFYJ5bp1J86yrGBfwBBAxjLmT5ocu5bZ0rTUX3dDWBhR4MV
dBc5JhQ9eY8NvKi5+hEpqcjZHjrIceemh35plndkcffXTVWyJENul5AaK/ZWC+KqaEsGeeeaa79dZbuzfffLMmIVDoRAKRKVEy4cKovigoynDfPsvzrJN+rRJlRLHGt3Nmo2t++rNu5rdrGJd+rb7M
izyZZ6yS+Zk39XTN37Y/T/treJ75WqVP133W6vfXCeUPEDGyhN+p8cADD+zOOeec7phjjhknllnfHGOTQ0yMEPMBxFtvvdXttNNOFRR5oYFZCIVOBbKzLbRM1M7en3hiGz0S4npDZ9y2dF2bJwoAzn
zoUiK65ppj/qSIF+LGMpB5bWg3L8DJ2KHWvOQYeDSPrgL2oTmeoUtX9Gy+uaI0eRWyeMHoxPjFF190+++/fwXEscce+9cAQZhdd911Wg5RuBhHCFuGCPH222/XREUiAhAYIiRmJJ6UBXEiSPbAyvHA
H0ICkdNL9mvb0TjJGXnMwNSqILTQ/fTTTysPjk94ssZshkWXMSkPXfxTLr5FvdnAxChR/pdffllZ23HHHSvduQyLrvO/LZrceMQrvulqNrp4xGuMbi57kZftwhNdssPy5ctnRIhCYKzKGiGK3mIv8t
dTBiLJIaYBojCvVA8u6AOI//znP9MAwegBBEbefffdSmCPPfaoRiVsEDzmpHdBwI8//riGOl3W3H333augvaHTbilXRRdIKcSLtQC13cqmTRzdMAwgeUtrrmTakc0ZfrYSD0fX0VsxD935RBj0zGMQ
PKI3Te8TiIsKdBWDm8vo6CpksF2kX9/ZZ589bcuoA0egCCDYlyOw1UxA9E4ZNUIUL0TsmQFAtFsGb3njjTcqgJYtW9bxmtmSTqgWJgmxYsWKuu9h2FnaGRowoFcdKrzJfHS9F6EwQESXcScBwjy0Kc
TRmQJFC4Y54IADqrdS0iS6ntMHuoCoUD66aFp7qEReUUkeBhj0w6COinRpbSDvFzwHEOh+9NFHda6TBGPiV8RpARNAHFtyCHzV9xBlnZQKiOaUMX9ACJFl3wKIdsvACCF4BYYxQ8GYg3gGFdbmUhBB
hDgeqwjZO48+svHGKCgRgdLUAEICJTJRGKOg2wLROAUfmYMv40VGimFgdBkGmNBFY6jgQx8gi2yKiIZuaAzN04dugCgyMxQd4lvIprvI266BbzwBLrpAYe6y4njoyiuynZCp3TIqIEZ51YwtYzZAYH
i3Xg6BOUwiOAkQBOGpmI4SXUdxQwIS1pi2tgowpz/f2pSi4ifKc8+47tti7RhIi0fbV1sZyLgU4xS00G/7MsYzaymRLePCU8a2rTFZvz8va3mevnau6z7ddj36SIQYAgSZY6OsC5ifNDnEjAiB2WmA
wFyZ3QeEU4a9WoSAToCgWIjlmQoD8TrGiqEiLEFSjcVs1nBvDuFi5KxhPh771Xy0rWlsxg8ZJzygQ0H4jbL0oWm+ayVty695aisvzyUvmq28dZHyJ/O1rbzWZ0zztYpnLV3PzEMzsqINtPQUutawDS
WHGJ8yypYRGSv0y1rKrIAQguwx0wBRJmHMtwzMihA333xz1wLCvkupMRKmFUqJl2nbaqxxWiX3hFaMNZ+ghCS0cAh08gsZuYq2CtkBJEVZO4puFeZauFUpzhZlfWPNs0Z4wkeVfRR1wi8ejUk7l7zW
MNba2tSspz90Wn0FVBmXeWin9ueRj1wixOflo5V86Nxzz+1sGRUQI77JpgQQ7GvLmhYhAAIhgNhq9OoaQSWAeOrpp7vrr7++Jo4ihHcREqK60MiYdULvTzwgEYNykvQRNCWgCZiiIP3GoYNxFd2Awn
OKi8daX+HplBSvByoKk3NI7FwDhzGJKpHZfHyb4xnQy5VawHmuhu9cWys09eFNBGSUFky5jrGNJbu5yafIhnaAga+hgjYDe//AlqKE7xgXXHBBd/xxx40BYW50vrLZMiYDonfKiJC/FyEfe/zx7uqr
r67fMiR9EsccD0Okz6z5lIpBSadryuknYcZFGRQCPJRvW0IrpwdbFCXpS/ikLPQpONf4yJoxmPWty9CJPpTIoyTDvApA0LeePsmZeQEf+oCRta3V1oAQ2ADNXOMBWNIKrPhua3iO/ADrOIwGxxMV2y
11SMfGArnkmhx4P+KII7pLLrmkO/GEE7qNCt0AMPON8S2DfiYCwpvKcYSY0upUhACIxx7rrrzyyu6VV16pYPDrKoaiJGUIFBgFAkxiGCgoZr/99qtKniKxJnGlXOtQIkWEhnM+cPCWRADjUvv0J/GC
n9CM8QDCJ32/HuJdDIJn3ua5cXm/IbIxJiWiwZgxaF24/AE2yrYdMTLwkoVMKfjQp7pmLAUtelpRjuGeR+65AGEuORxngQn/Rx11VHfZZZd1J554YgVEjp2JySKEV9eDgCA8poZyCBNEiMdLhLjqqq
vqxy1AYCyKoqQoGmMpMRbFiBAE5YE83BmZkuKt8SbKhVb7nyMgzwQ4IEq4DtK1/Yp26IaPtHhUyaNlDPTRZkBejUdHyXfeeadWHsdIAT565nvGSO3WGT4BJiV6wRNatgI6oA/gYzz0gZx8AM9p8n5j
3333rdFlkkzo6KM3vAMEYKMzjhAjQERv4a1GiNEpw/bPLuMXU/MBxJNPPtlde+21laiQTxm8lmIieIilxUQUAbUY5SnARHjK4FEU7Ln19tprr+7ggw+uYwKEKETbB0Hu2zGu2xL+tAGEFijSAi5jUK
jE2Uu218snfzwDL4W1hgNWQKEHIHbPOegDKPClWD/As74IBAy2Iy+YGNI2ZZz16Umf+fQUh4sMrVyuyQoQ1vYGVDRGw9fOCy+8sDv++OMnbxmzAqIsPCNCRKBisEnfMiB7UolhtARSXatAQNmeUTaQ
+VFHIkMMQNgYncLae3SzXnhwP6lEqeElbYwGFDyHB4sOzz//fDUa4JKT4YGA58qhnHIYDLj1AwIe8Rs+0LA+eQGD8UNHtGB8tNrX6GS0Fidxna1lSK7Qsa71csrIsdPXznEO0SwwjhCFv2kRglHaCD
EthygLVGUVYSjn9ttvr+FMosdreDDGo1iMKzEgZiOcVqUYXkAACmL4KFlmbO0Y3nxrZW7aVuGV4AL/4DclvLdGYzAG8gsxeQSPxhOwLlu2rG55lMhg5Mdnv2Z9bWho0Qkt0ZHubRG8W8RgVOMi+9B8
etZPH3Sh0Cvgijh4B9qzzjqr/h4igDAu7tKeMsjClnXL6AMC4lMigB/JPPfcc+NX14wmRHrtSiEEJByGFB7jeWvYKMw4NBVMAIP9zlbRvteI8bWt12WdusAi/SGnQg7KplwhGBB4nIoHvFKefMHWEI
PgKaW9zjNtaKQNKOgMCIT68u9karSwZaHPWYCO0c3DF/1xJnT007N+zsXrAwh5Wn4PkV9ft7yNI0SReSIghMFEiAhRGS9KsmXccsst4xdTSfgoCqMJtca3oRTDiucqxnkgMAABxu13mCJYaoAQYHj+
3yh4BIrwCbwSTnJyBA7TAqFV8kL4Y+DoBD2g4NnAQNeujSG37ci1yErPwIIfWxg94ge/1gAI25Atw4spW8YQIOopo9DAwyAgCJYkphWsKqgY/NkSIfKmkmKcrUUIzDAwbxJeCQdYmI3HWy/o1h9ax5
WXJkKbtXic59YjrLoYim9lmeua0lPxGZ7JxzDAwDgB7VzrzdUfWlpez+CSWqcF28iKcvwESJEALzmdiFgih+M7PdMVQACKMaINQJx33nndMeUndP5ZZt+haoQotNBeOCCKcqC2BUQbIYQxjBCAIgHL
iSEKRBTDhBMxMCAyQK8w3BofCIzRqn/VA+cyxlB/ayCO4L46RJFJCVApdzH5Ch1G5+UBBZ3zdnrQx+AiAOcLIDgTftggEWIaIIqOzf9rgCie3eYQlPBnUQojt4Bg0EQIno0YL4JcwumTR0RQLQ8Qeg
HlhPL2TAIpktiPzcd0gKH1jNIXU/HkmVTwmAoEbclzz/AT/toxa3uNppocS7R9unwu8E6E3gCCTrWOlfQlOgCGZ6JLIoREdRwhAojCd1uSQ5BtcoQYAkRhsgKi2TL6gBBGjUlSKcQxaE4SBBUhVHnD
ySefXBluk6J4X5T93wQDRVEMPvvGDyBjMPfxuPS1iv6r16GLDgOLDP7Jg5OOLYTBRWX6iZ7jjEA0ERC2jEkRYpSnTAbE6M1jK9Q4QkwARJsFAwXBMKC4BwIM2wYcVW0VXpY4whEuzLrOVjFJ0ZOet/
wu5BqvKa4Zoy19eun/O6MXGvTGg3k6UDzyyCM1yZSTcT5j8EZ3WuNF6MEIEUAMRYgCOnJPBET7LSOKCSCeLj/Dv/HGG+sbvCSVGASItmA2QmmTLEG304S3kH4ibusgDOUCQ6r7SaVvoEnj5vt8CBCe
odPSynU7Ho3+uPnSnW0cGnEkkcAb0/vvv7/mZ3EgbWgbrxorv5DL2bptyeeff379/F2drgeIfMswdwYgJCEI9N9UYjwMPvnUU90111xTQ5i9K1XYSsnYbA8JZZIdH2pOP/307sgjj6xgyLaC2USGv9
PzwuNQi++2RtkZ6z7FuJT2eZ4tRouGbYMeV5RE/dFHH62njuQSokSiQ/gWHRxVgcE4znfRRRfVz98Z2/LW5hAcfNqLqdkAkQjxxBNP1I9bftAKDFDlPT7DQnRqFEZZrj0XJRwvzzjjjBohRBUgSHQI
IDAcJadthVjodctL5sb73IcH16IZA5hTPapJavu8DK1rjcUq1scPUDDySy+9VL+rAAdD5sVf+DJedJCI2mac5jiez98S+CpPA2p8zgoICcwGEyJEBURhzufvK664onvhhRfqKQIYfH8QIYQrRlcR93
5CdYLIteMl1JpnTOrQVhFB11bBQ4az1/Igfe17EmCQmDEEoKTOtoWFv8XiN+tpA4gYWnLppCcCcEJRAt3Q9twYtiSjI/3ll1/enXTSSfXXcOzblgCCfdlkWoSwiIXbX0xlcgCRCPHiiy/WbNfRUqTI
lkFxjIxZyaMKENqMzZs+tBIdsi9GMHTb6/Cx0JaBk40nIlmX9zjnixR5V8L4wEyp5lEOOZLFG8tASuRsgbIY/PblQw9dhkty+fDDD1fevRogE7oqXhxFHVHZkox+D3HppZdORYjS3wdEvmVwjMmAKE
jpv4cwYVWp/m3nDTfcULNeRo6yRACG9k5BFIiSIVihbApWW0GAR1+bIEUpi6Hg6gHF8BRre0MbLfmM0MuLAlyRwr2vjoABwHnxRtkUDCgKuYAF739nqXovgMAXnm3V9957b/3eQee2DbylytdEPkkl
APlNiTeV/rHv0hFwWn6rfgp4ZgXE0CkjgBCubrrpppr1Mno+8Lj2bsExMv+CCbMKJhVKTGUUQgCEZ9o+APr3dZEJfxJa8Zm1zecx9lQGZnhGxzPjMjyFMKxnIh1eAwgyAYR51vVmECCMB2wGwbs+NQ
XdhfCeeUOtdZPviHTyiLvvvrvyGEDQXaqxZCW3vEPO5l9uySWGANGeMgYjBKYmnTIw50e211133fgHMt6j+/0CMPAoCqcsYGAYc1pAJBoQIIDwbG0BgYYMGz30E0p5lU/KFCQ5o0S8Kr4q8iZgEukA
QmF4Y2P0RA7rWD8RUD/ezVf1AUJkq4ut5R9rBuxkBIg777yz6h99fEen9IlvYCevbSO/uvYtYwioNUIU4CjTAKEjOUT/a6fBGFO9h/Cra16H2GGHHVoTl7322rsqMN4eYxMmgGgZj9K0gKNVWs9qr2
vnLH94jzDJO9ABSJ7s3s/h5AVkBBTyoQkMlIc/9ClYaw5ZjSGPtTxzCvNs2bJldUtMdJCEKuhZ3xjyL0YJIHi+6vcod9xxR9060MFbGykCCEmoLcO7Hr+6ngSIfO1EByBsqfX3EAEEIYYihOcmPV9O
F/6DIbzIV0qA2Hffqa9tMTilqpQCENl3oyjPU9uxAUBaNOdbGIXRgYKhGSsfzDwXKezDeCEHuokiFE2R+tBOXtQ+N4d8lJ/zumc59+sTnkVJa/8VGYZkRYMOU/MtyfcNTgAQAC6Kkcf4RAhy9wHRp9
GPEIOAGIwQZSXEvEK96667qoL9kveQQw4e/Zx+m6qI1sCMbg5lK+4pSu0DIs/rwPJnkkKtp0ZBxqHJg5NIOT0YA/GUBAiiAD6MozDzKBFwrKUfqDynFGt6Zrz5+JVn6BNJ3OunUN7ombevth19i1ki
q9aRUg7hh0q2Bc+ANFuH+ySg9IEnEUJSSbbph86uS4TA74wIIQlRhn4P4Tkl+8DivzG1cuX35UhzdNk29i+A2KMqtw8GDCiYNFepTGGs1BYUGZsxbes6xVoMyxiqNRjD+nmHb+sTEYzTz4t4sGvzE7
GABc/mei4iKCKZYr7nqrnWwKdxaPNQ97YKQJCbANlil/CArsjsR7/yGdepgInfVOAGGPld3TLK+4hWx+GxRojiQIpAMC1CzAcQfrBx3333Fc9YWf8rZ8uXA8TuY0BQXGoYoPBUhD1XjUvrOiXz0ua5
lnIInbDomsEZUR9F8FjKSJLZ7rGhozUHIPolALE2I7hX8OMZIGT7ASpgUJ1I3GdbAiA0tEN0+nSH7sML2fASQ0dG4PcPjOQLtkqO0Fb/qQC/uvaCakif8wPECCl9BqnFSw+A+PHHHwogjiifr5eXvX
rPCghKVhFOzRotIDzT3x/bMtyf31+HQiS2wiIjCf28kwEYjAcnEsTw6DGMsSrj6WtpxQDWtF2o1mIQhVE801oPGNEVJRgeTYaxji1G1Y/WQkt0hrYanoAi2yBZGVWkkDw7Mosgtk1O47h58cUXd/6T
Qv3tAj8VEKOdYXKEmAMQvroh5kexfoAheSP0bAaOcNoYoG0xl3vXSv9+6unUXxFgRXmxJPPnEcZ6X8BAivvQGgJCHxBTq645TUX5FC7SAIH1AEGfEu+3FnqMBjx0AxxehOUovlBAoKVorYuuCnBohA
d9ASEQ+C2m/EIkpxs5hG8ZDgALBoQFTZp4yihCixAPPPDACH0AcUAFBE8IIAjSGjPGwXyKZ+34zGnb/nXmanmI6KDyDl5DeYwkwdIqIgLj8GCgTfLleejjJSWGiBEYVzjmSTFKxphnXLYPhrEmGrYP
WymQou/5Qgs6qeEngNTqyz3A4pUNJZ7eVziiclaA8NuTJWV8vyRC6EnuOD52WkwZ+pbh+eqiACFpDSCOHCeVAEFBqcZH0doIps2YtMYqGd+/ds8jeKvWOApyTSDHq3ixvoRv17xXopTwLYIAQ0vL+i
n4UyiaJwr/AEHZ4R3YXKMfQ2jdiwTecIoOOZ7iVWkBOIl+HVj+WL9frZOKv1yjG2BwEE7rW5PP5XKb8SljJFtoaPMtw/UwIMqkdBjUFkK8UwDx4IMPjiLEGkBI3PSnmhehtREu6w2NS1/mtvMY3D9g
AYA2VFOKZwxCKYr+RABgYBz88dTZwGAuPpVEILmKLYn3mw9Q7akmIEXb3Jw4klcAAYMp5re81YcT/liLbOFHmxogaNFNRcdWKsmURzzzzNM1Uv373//bHVpOG1mrJVkjhEBQbBS71whB4dMiRFFgvz
DQu2XfFiGEaAmLHEJoHAKE+eakhKH2Wa7TZqw2z8zjqQRlIILri7fHGP25bfgWIRI52nH96ygdCACQgkUKQDKfnNYyTp/IoZ9xFBHJOG22CX0iR7YsoEhfn7778JB26Jm+PiDogZ7YUS7xwgvPV5r/
+tf/dAeWt8rm9Eu1e/O6odrR/1FnDIgyKUhpJzOAChAiRAsI41tAZF4MmvuhNuu2fUPzRABGsj1IliBbYSjAoOSsFWUDDiW4Zwwf3rRD64d+lIyO0Ism44oK+Tgm6ih0pp8R8KegKWok8Qt/thH/VT
25hWfhsU5q/gQEadPV3udam+iQNkCWVL788ksVvH6QtH95PZB5WVPbjxAzAGFSNfBI6PHkESBk9osJCOvHkGNao2ftPUNRMq90vBIphHVFEscDgUJYZkDjgZZxjOO1AMEgxigxGmUaj48oLQ7C0MAA
SLYe0QE9xboMIKkVKazhGYBorYsXc70F9OIKqACiD0p0ldDPfX04+tP2tdcBg7YFxCuvvFz59R8/32+/5XXt8qddciqHKBEFP2PHbiMEQkOnjGq04mkA8dBDD1Vl59g5XmgEmmkUy80k4dvn7bX57b
1rfLUKBwygYDBAoPjs74xGOQzFOICh6E/Yt5Y1eEjyAHQYy3oxmnUBgFEliTxIn2INQECHIfACZPIN/IoCwARIgODaeq1sdaHyJwZ273qoZEy/xYfaB4STBl1MAWK/qf8LUm/tGiHKloGnsR3/CYCI
AqIsQhOScnmbVjhW84wwrhXGJjzDBRDCPqMDRYzOmAxjbUYElngz2oyY5NHWYGwLCPcpxpsLmGiIKgChZB1r2C7M8yxAc62mxMi5H2ozRqtER2nJhA+5jy0jgDj11FPrP/dr/6d6WX9WQAjFhUpBys
x/uUX4JRssnTNCIBSjhuhC2syFdh7HoF6pUzrjAUQbEVwrFM+DAQI4FMaioLzWBQoAojilykSuUvuF4WxDiTrWZVgRJsU861kXnbwP0Z/5WUMLaP0aUMTIWXuoNSZVf67J43oIECLaGkCseQ2f9Ssg
PinfsIos48NBIgRAWBgg2n/9bXJV3gAg/IObLJRxIfZX2hinBYSsmbKBgwGAgNeKBBRtjmsvYbQBCQXx2gCK8EDCi82JkYwP3SjXPWPpE+atK/QDHmPHkMYDqWiDTzTo0Px2nHXQy5alta4xxvfLbM
/0pT/X+FDbHEKEAIhTTjllFCFmAqK+hyiAwG/sOD52jgEx8Oq6Kqgwv6KXQwBE9h5CGbc2JfMJSkDGExl4oC3Ang0sxlEyj9Pao/HBcG1hIB+ARJgcEa1tPmNoY1zzomjX+vAAhEI+hXkVDYxo6lfM
ATz6Y5BsbWnJgAYQSGrxKeLgfRLtlo/QqMRG9NpnxraAwIdjZx8Q/q/M/XVrhBjlEGsFCMqVVLaAiILCuHboWdvfZzDj00ZYoPAWjsLRZiQlngcQ+TjTrhlDiS62IGBqjdDyMnTNqKIK7xYhbBsBhf
H4VKtiS4QA3CSX5qLHWIwPVADRJqeRM7Rb3j1r79vr9HmWig79AIQcwtvKNkLMFxD/BwAA//8VFrLwAAAqGElEQVTlndmPXMeV5k+utS+sYrFYXKu4iRQpS5YIazAtz4OmbcntVdPz4p53Pxj+W2zA
hvcXAwYaA/jB9sgeW/ZYjWlj0O3RvpCSRXEXtyJZrCJryT3n+8XNkxV5K7NISnJbrQnwVtx7Yz/ni3NOnIibzFy8eLF5584du3TpklmzaTMzMzY8PGxxyGQyls3l7Ny5c/ZP//S8rays2kMPPWT79+
8P+UdGRuLs4Z4ydwtNtRcHL+MxaeQpl8u2vLxst2/ftlu3btna2lp4XygUbHBw0MbHx21qaircx/WR9+zZs7a4uGjZbNbieuN8ve4bjYZxUS6fz9uWLVts9+7dNjY21i5C2srKil2/ft2WlpZsdXXV
arVaSC8Wi4GW0JNrYGDAeJcTLbuFND3I0+2dvyeNiz4SQ58rV67Yu+++a2+++WZo8zOf+Yzt27fPGvX6hrqgKfk1QNu5c6fBx0wMCCqd2b49JMQdZtCdgFixY8cSQOzYsWNDfsrejfi01SswwEqlEo
AAGLjnKpVKgfjcU94JDiAmJiYCweM6FxYW7NSpU4FR5AUUcYAxfX19gdnUVxfRaM8Z6nlJ4x1AYBLQVhwA6I0bN0I7gKNarYa2qHt0dDTQB2L39/cHMDhtnAYee52eznM6zd/xPn05IE6fPm1vvPGG
2h02ADE31x0QCIIrV68GXnUHhBjRVUKIkBAPCfH880iIlZ4SIh6MD3CzOD1gykPgmzdvhgtCM+sIzFJnIM/cQ2gHBAT3QL0AAuIwc5EmaUAMDQ21JQv5GRftEceBNMDigEBSxCEGBLPOAUt70A0pRl
nAgaSg33HoRoM4nfs4j98TxxcMvnz5chjzm2++0ZYQAIL+N8XfOLiEyKifHYAAWagMKu8lIQIgzp/vAASiCADBFML9giHuXHwPgWEmzJmfnw/qgr4BCIgLc2nLAQGxJycn2xLCieQqA0DQ/3T/6DeE
gElIpTBjJEKJ40B9EJS2t23bFvJTn18AALUEgQEvEoIy1Ek5+g346CfShXvGQHnyxcH7SOz3nu55u8W86wmI2bkEEKm2wngjCQFgg8poA6KbhFDHsrro/LkIEMeOHQvic3ukYtID8IHcbwwhISrAoG
/MWAgN4SEw6YRYZQAIGOYBAsGk8+ozcbe+wZjp6elQjjphaC8J4cylfWiBNMImIKZuV22oFvIQiBkHZclD/wAEEgZw0H/SnMHkQar4xTOXB8/Hs997TD0O6A0qYzYBRANARKBIS4gNgKDSMOM1Y+KA
SIEIENdVBoBAQvwlAOGEgKCAAEAADAbMvc/AtFEJgxkDTIFBSIZr166FMk44jxkfDKEMM5j3tAUIqT8OpHFRJ32gDaQTYCBOz3RnIrGrKco4gCE8as7BlG6LZ6eBl4/z+L2PhZj6HRBnzmBDrBuVc3
MtCaE8cbjTMippA0nZHRDM+BgQoDQCxB/+8IdA4L80IOi4DxQmMcsdFDCGNBgBQyAuQGYGAgZAgw1CfsryzokXE8SlEOkEAAaTiOPgZR2gxLzzC+YBKi5XBRAZCYI0oF+kOXO5p9/hUns8myZvAuRS
ACRtUC9jpBz36eD98n44IJAQiQ0x0jIqI0Co3x4CIKQy7g8QKp1Rp1xCAAhEzV8SEAwQxMMwX1kwWNQGz85gBkK/sAG2bt0amEE6eQEQwPGZ5kSIY5ciSAbywSDsCuI4OPBgHH2DWfSNy9UY7+kPgC
Af9TkgmHn0kTTGRVqxWLC+IsDIKr+YDSDqSKGGlcpeb6MNiG6goE0CMZcDAgmRLDtTgFC/47ApIN57771ghWJU0nkPgaAQXoM8p1XGvwUgfCbCVKxm4ngWwyCCE4JnZjZ5YiDAAN6HGegDimIHHTGB
esgL8eOAWsHPAV3IQ36A4BdAhRkOLGjmzOKechijbjf09/fZ0KB8EgXZI7ZkmWYpNNe0fqtnxqxSzdmyfD2VSmKcOvDT/fI2PKYP0OvMmTMBEIA7WXZKQiAl1W/PS4PBhsCo1Hh37drVqTIABAMNq4
wIEIJzIBCEOtsBiKMtG2LdkcXgP4zggGCVwOoH0U/fIAh6mJg8XIDAGQpDGCQBJsIILoDhecnP/d0CY6EdysJIX005GF06IJGwVeLlMUTnoi3yAUqMXi4k2djogA32162QXbZmbd6s0VrmZocsk99m
1cawrZaykhQNSYzE5wL9aTumsTPX4xgQJ068KWk3GgCxTzZEm07ql4dYQmwAhBxUiYRIeSqdMHkRBgnx+9//foPKgOiEuLPe6PuJnZiIdF9dOHEhMEzANgAADgzeUw6iwQDENBfM5B31ABbARb13C4
yFeiiPjZI2AmmL9qkXqcTymHsCafHlNAQMDzzwgE1NaMnZvGjZ+lUB4pYKrFmYStkBiakt1shNWz2729YqfQLbbYGqJmmSLFMBaUxnb4d2OwFxQuMfsc9+9ik5pgQI0YeJQ34PQUJomY2EwAPbYVQC
iCAh8CukJEROBdKAOHrUJUR3z6Y3+n5iOu2d5x6mw3AnPgMHFLwjn89+n80MzCUEMQQEQBAA5lEPZSlHeS4PEJzZiB0B0AECMfYA72OCUif+EupEStAnAgCkLz6rKQOgJ7aM2aFDczY5plVM+S2B4b
LWppIOzUool8kWzSQlLD9jmb7DVqqN262lNUmKWpBW8IG66aMH6vY+xYA4eRJAjHYAos44ld9DvMrYFBA+4ykIcnFbM0CXEDScAGJOy851x1TI/yGpDR8kdcIwGAjh0ZG0HxOCPAR0Jq50ZrUzxInn
dTgwkBQAg1nu4pS8lGP8+AuoDynBO0DlM9P7Rn+gCTHB37sxCRi9HzByaDBnE2OSPPmb1iy/I0BcVyGtcJoyNKkgI0ZntOLITQoQ+63a3GYr5QFbK2dDP2Em9dHPuC/ebicgTgZAPPVUIiHC5NEEWI
dDy4aQhKC+DkCA7g4JIUJ4CIBoEQobApWRBgQE9A567OU/aMxgmXm0iU3BJhJMhcDeFjGDYkag6128k8dnP3moC+ZTnvpYnnLvKoi+AgDKu3+FegmUdcJTB2VY2uKbQfJg29AewVcrAMqv4eEhGyhW
rGBiQOOyNSoXJR1uh/wb/mSHLVuYsXpuh1WaO6U6+kMbtZrsDgHCx+5j8r4xJjarMCpPnlwHBDaES9MYEJ7fAcFECp7KDYAQg9tBhERU0REA8bvf/S4Q89ixo9JNiWPKJYoziLLxfbuu+7yBmRAfsX
zhwoUglr1uBpFuA6bAANb+6GvW/85Ez+vEo263ARg/QINolKE8HkxmOMHrCA/6A5CwGQAE0oFyzijyuoqjLhw+22e22/TUVhvqX7FM+YRZlRWdpFyjuy2TyUgi5VAdO63Zd8zWqmO2cAvbp9JWQ/H4
fUxIPQDBDi+AGBsbtaeeetocEHdTGd0BEbminQCxygAQNOyAgHAwgeBE93IfNHYxj2RgFcRsdl3uaS7yvS1mD/1hhjNAZqvPXPrHBTG5YBx1AjhWM9w7ICgPIJzY1E9+DFL6A+GhA+8I2AtcAAOAAD
Kkzaxm566d0za9dcQGi7dkP75mzeoV1ZuoilB4wx/6KQlY2G6ZgU9YuTFli7flyi+tu+1py0FBH6GHz/h1QIzZ008/rYnbkhCtvnpzIX/LMeXb+p0SQgU2uK4hoIjMQNGXzz33nBq+bQ8+iITAhkj8
Fk5sb+zDiJ3pEBhG0AZEhgDofxjCLOWegDQBIEgKbACWefE5CcoTPHYGM8sBBPUwTlQGyzAHOu0RSEcysMQEFN6WG4+AFRASAARg3LNnj01NDtro4IoVM/PWKJ9WRxekyzHwQtauf0IfteLI9s1aLb
NDBuYWWynJPyH1RL9dRZHPQZsGxPg4gPhcJyBaY6HRtlEp/n4gQNy+vSRAPBgamp5OVhlOZI+7jvI+XzJQn4HMcp+BgAOmAAYY49a92wc048wBENgWbhy6/iWPA84BAbGZdQACRgII6nRAumoh9qUr
9dIvxo1EAYQwi3TSZmambXxYDLQLWmZelg2J30H+hwCGlhFpvmoAJLjR8WYqyg7Kxtxqzfwu2RP7bLU8KNWxKCCuqyinN7QCEFc1411CAIjPfQ5A7Atj4JBMq2GGf++AcJuAQjToEoKGkBAQxAHRTU
J4Jyn/YQXq9HphINIKMHggDQYDIGcizGWWMmvppxubMJAAESlDfdgoSBwC+WZnZ4P6QCqQjmQgHUZTjjq4XGxTDhACCOhHuxiSkxOjNljQKqT0RmI7yOcgnRH4ojWDmC57TTZDCCw/5aTKWDUBhFYc
mYzOeBR2BtWBlFi4pS32tWSZStveficgMCrfki00LkD8XXAgAur0qSkmAKoP/naVEBCz23kI3NY4Rs4IEL/97W8DII4cORIkxN0A4UxMRnx/f72sx/QPhqDzWRXBLHQ+Yt7BgBgnD1IDIkAo8gQPoY
AB05jBzkx6hJHIzGKGxfnJRxtMAKQRNgYMoD0YzsU9gbaQPm6DIDkntgzZyEDD8nbVGquvW6N6VTnlHJLDGje1ZXX+ID+h1aYcUgrNxqoExIKy3BEoSrqwTzQhC9OWHTimFce03V7J2spaQgfGTJv0
iX47g5m4b7/9loC9xT7/+c/bfu1KV9Q/3NdxcBuCOjYAghkCgrAh0hKCAkUNnuXMb37zP8OMOXLEVcZ0yE+nCM68OPb7uDPv5x5GwxwGAqNoE3UAcwECjCUdxkEsJAUg4uKZfsBARDni3cU9+aiP+h
1YXo40iE1b0IG2nAkwH2lCGn2iXfqBlMBPs31qwApNeQLrWlVURN/aYqirmZFUyO+wTHHG8n1yQuUSo7xZv2O1stRK5YrsDJVrLoc+Z3Kjli3ukgdzp1Vspy2v5ds2jAPbAQGwz50DEG9LQkzYF77w
hXBupaKxMSbyeXAAISFQkR2rDABBgW4SgkYdEL/+9a8FiFsGIBCrrDIAEESB4M789L134oPEMAyxDdEJzGAYCxMBAmnEpMM03ru0gOEw10EBM5nhjM37TH4vA7iox/MjWcjvYICwtM2mFf0ADJShHX
T30aNHbJuOXmbKb0t8aFtALupGfc1Y+jWzk5btP2y5/r2W75+xbD5Z5jdqy1YrXbF66Zw1Sn+2TONmWPJncjqEI1BYYZeWoQ/Klhi26zc4bJx4Rr3/MBhA4Bv585/flmE9aV/84hfbgGD8cYglxAZA
UElPCSGiQQz22QEEuvvw4cM9AUEH/fIOeKf9+f3EMAHQEhyAPjtZJaDrEd20BQMJzliIAbOpw6+QQX9gMkwlJo18Qecqpi5Ag2ShLQ/kAxC+7PaytDM4WLSZ6Qkb7lvSMvNVzfhL0gfsu8hArclw1F
5FfviTlh+cs3xREkYMJzTq2tqvaGd39azVll+RZLlmhbzshJxsHuwMOauyWoaW6lttYakkFZEcQIYm9JOxciAIXr7zzjtBUgGIAwcOhIkRdjzVbw+xhNi7d2+nhKCSICHSexkqDUECIKQyfvWrXwUd
zibNbBcJ4Yyig1xxSD/HafdyT3mfobQDU+gzNgX9Z4D0kwt1AHMACVKCsg4E3jP7Kcs76qQMMSHdT9pyUAAMlyKAiOUtohaJQ5sFnXMYKAos/aWgLpprJ2VDXg8rzHpdEqsiFaS9isLIcSsO7bNCn9
RBri+026iXrVrWZtbKGaveeTGoDc5M5HIJHVlxZAcOWzUzY8ulQbuzkhjELsmQThi/SHsAgd30pS99yQ7opDg0YNxx8GUn4+4NiJZfwQtCnHVAnLZnn302GFiHDj0QKnGV4YyiHGUcGF6Pv08TO073
POl38TPlvQ6Y6UxHQsAolpnMXNIACDMGQsX9Ix9EJPY26a8H8jJmAvXTHsxGNQIAyrHspQ4kEe2xRMWe2DKxxYaKJcvVTlsGVSFDsllPtuRrkg5rJUmq3DbLjzxqfcP7rG9gUhuHiTSrVdesvHbTKs
sA4mUtU+fVrqSTpERAlLyXmcI2axZ2Wz1/wG6vFsMqgXHSR8aJxxWDm88PoMWXv/zlDkBAFw9BQkjF3DcgWGUwg1AZzz77PwIxDh48FAyRNCCcYTEgnIF0pNe9d/J+YgcEhEAS0Cazgr4yI7An0Knc
M4NhMlIBRrrvAkYTeAfzqZOZD4PpK2IYAPAOhrOqoh1WHZ5Ge7i7Jyb0wdBWHZnTMrOxKo9k+ULYzWw2kjOaAGK1JGs/s9Vyw58QIPbb4Mi0pEpiQ1QrWlLeuWbl5dNWX35dW+Q3bKC/kACCToaNL/
kmiru1KfqILZdH7PIVvge5E1QcNgH9wqvLxzrYNwEQm6mMboCAmL1UBkSJAfHLX/4yoPDgwYNhqeKAgEjpy5nvcRiT6vMQv/d39xPDPJjlqKd9ZzrMAhDMZN7DSMQ9RPOLZ2YR6dhFlAEwzHg8lcwc
ZhyAIw8goR7ART4MSdogH/VsGddR+2Edxctc067268lqQY4m7x+bU6uSENoID6K/OLLfRsZ2W7E/8W5WSlpBLV20yp3T1lh7W8vVBR2kwd+RqDIhVKDQMlMu7ezQMbm0t8mWaNjC4mroP2NAffqpKQ
Dxla98pacNkVYZAD64rtuA0Azxk0FtxqgTrjJAHYBAT2GosHalUV9lQLT4guHOdI+pt9d9u837uIHYtMkspV4YxeyHuX4xuwEujIOBflGGzSfGB3Dc8cR40KmkM+MQrUgQpImPl7pcClGe+sdHstaf
W5C6eM/qa6cSn0I0FlcZVRuzZnF/kBBjk4oHki/BymsLtnTzdJAQGbm4C5klG+gDEFIZ6/NIqxK5tAf2WS2rndD6pEBRFwiuBL4sLNwM9/giAG8MiGBDRCojrDLkmGLCM96egBjWTPBAPwIgRAwA8Y
tf/CI0zCdtzCJmRjdAwBwYRewASMftNpTn/YS4PtoiIDFYITB7AQeMQxLATNJgLhfEAChMAGKXGqQBBN4jCSCiqyTaw4agLpdOpJNv+3Ytv/vlhVx7U6rivGwHHEx69qAh1qUySjIqKzoiV89JMkhl
bJl60PqHpkKu0sp1uzV/MgAiX79oRR2xw6gMgIjqyWS1DM2Pa929x5oDD9niclES/oL2Yy5Los2HfRkkPmdVnnnmmURCaJIElej1KF4WDfBU9gQEBdISohsgMNT4JoPZBSAQsbFkcCB4DCH9oj/OSO
9b/Bzfe/pmcZzfRTNA8OUnzAXQpDE+pIdfAAXdDyCY7YAIYNBv3sNoAIV0QHoAKIxI3tEG+ah/dESe0EkdpsndtNqdl+RD0FmHhra2m8kS2fvPKqNSlZexPiCvo/wXAsTkzCdtYHh7yLK2fNVuXnlF
RuVp7X3MWzG3JkBw4j0Bu9cTDtLodFW2b5eM0+O2XBm39y7dsIvvXdEK43xYZQAIDgs988x/MdQ7Yw7LznYlyZE7AAF9NkiIc9obYJABEBKZ7SBmUoBZgYT4+c9/Hiz3ubm5AAiMuBgQMMiB4DHv0l
e7ft3ETI3v4zy97uP8Dgjyenv0gQAzuQAFMXlJAxQwmPyACDVDGowHKOnyDixAAhjwSo6NFmyob83yDTmVlk/o8Is2sHQKiqVBLPvagKj1yZegL7eGD9jWnY/b4OjO0MfVO+/ZjUt/CoDoz2q3NM/O
rQCR1ZI55Gj9UV81QtkS2yw3dMQqme22tNJnFy/dDKetT516J9iEO3fusL//+/8qQBwKgGfsGly7ptiGmJ2d7VQZARBdJIQo1QYEa9uf/exnwXIHdagMCOKAgKgxCPzeY2cSPeI+HeL0dNr9PFOPMx
kGcjkIqIf0mNGen3wwmryU934TMyl4jyQBOEwexj2jwy9jQ8pfv2AZ3NOlC1IXS0l3U2MEEDimytW8rVYFOAFiavcTNjS2N+RfWTpv1y/+0aqSEAPFVevTMf2iDMqsANEt4PLO9sulrWVoNbvHLl1b
s1deeTV8+f3WWyfD5P6Hf/hv8iof6Q6ISGXM3i8gmDEnTpywn/70pwEQfKhDJQAC0erMjGMI6USN33PvIb7nnT977PnuN06Xh9mEuD8xUHq9pwx1cQEIwEA5ADOmfZQdO3QepE+f9y2/LDCcl+MiOg
kVjZN6KI9hWa5m5FgqBJUxtfdJGxqfC5JkZfGszZ9/XoB4V46tmtSFdlUDMNfpRT0eOFklEWEZucCzQ4/a/K28vf7mCXvhhRftj3/8Zy3Bp+xrX/uaPfzww+8PEIiUHXgqI6OSxjlxDSBee+01+/GP
fxx0FNvf2BF+qJUZ5ESlDAT0Z4+dsKR74F0c/NnjOO2D3nv7HseA4B39hNEEVy3epuflPWOFRlvGhmzrhDyU2etWu/2C9iDeS+yGoC685HpMHXV9nVWqyGm2ps3vof22be4pAWJ/yLSyeNrmzz4nT+
VpGx6UM6zI8UX1q0WjdWHfqjO8l0rp10pp9LgtrY3a6XPz9i9/eikY/2z8feMb37BHH320bUOs96Z1bL9lQ8zOplQGy5RuNgSEckC89NJL9u1vfzvspLEZwkoDcYTdAWDQxx6c6B47KOL0bve8o4yH
+N7ffdA4rhMmefC+8sxsJpDuF/QBEEODQ7ZD+nliVLaVlplZlpkr78h2uEmJ1kXpzkA9jYY+16vouNtK1fIBEJ8TIA5q0Np3uXVKgPiN1eS6Hh5S3UUk7DogqG29t1630gsTEhTar7Dttrg6bP/6wl
v2k5/8JNhAX//61wMgyq1Vhpcijm2Iubm5ThsCQPSSEDAahr/w4ov2zW9+M0gKVhf4IQ4dOhSMS/z56FQMLTfUHARO6JgRfu+xd/Ruz57v3yp2MAAQ7gkcXt3LTwsN8X3Fn3X4RRuDZVzUrS+w0p1r
lQtQ0Z9SpS5mlMPm1uTep21w/EAosbr0rt08/1zY3BoZKoYVBuZDND86a26hI5PXKq+4zRryYNbk0n7t5BX7x3/87wE8X/3qV8NhJt/+jitgRXW5JSF6AiK9yoBBMSC+9a1v2csvvxzOIQTfvZZnrD
QACE4bHDSAg1UJopVAHb0YvVla3Pm/1n0yq5OTWKgT7CU+uJmZ1qnuwi2dpH8xsR20tR0OznbraAsQJMHDsgCxvFKRc0lnEHY8af2jc6FU6fZZW7r0fDBMhwWIYkEGJcKSq1twQGQlmfFN9MulPfKY
XbhSt//9x38NHw8//vjjwQzA9nGp51W5hIBPHYDA5RlURpdVBgxzlQEQUBmvvPJKkAYwHbAgGVi3AwxAAVAgHOks3bhcalAfkiO+eoHFO/7XimPpgPRESjLGiXEdjNHKvKjDL7XbL8t20BdYgektDv
XscLJ8xBexsqozHUX9es3032jXc08oUVm+YCvz/0eOrUtSS9BNy+GudXk7rdQQia46bFMYe8RurY3Zu2e1SVbLBRsP/sRb305vJIQ7pgAEPAyu63sFBEblD3/4w7CsoREYTeVczB6QxjvUBoDAqMGz
B0C4h6Dk8QuQcO+qpevY/4ovXTows7AfxkbHbM/ePTYxovGGZaaODKxKXegMw2a2w/oQEgZWtaexsqrVio7G9W05bvmBHSFLfe2ylRdetEztmmilVYgkRPeQAkQrU6ag71gHpTZ0smq5NhM+GoY3YR
zqPzG0JvD+roDoaUOIyTCTXzZjleE/eQfzCRCMslwQjsaQDsESF+oABPeuRroBgs7GgTruJ8TlP6yygZAaGwBnDJyg3r9P1viQjqPdeVWe6XMBDE2pixBSY9jQ/9aYkj2Nqja59KXUgFYYMgpD4Hj+
6mltamkPI97USlfkpEqTKNsnW2JMqmhWZ3cf0fH9rXK7c76UndxkueySmSpx08c2xAYJAUN72hCa8a+//npbQsQMhgEOCNdVLjFcCrgkoCPkd6lADOH9Ip3g6cnT5n8pCxAJ1O31b14qSQXMrlu9HD
HB+wRNjh9/zB48ctDm9soR1a9DLIsvagPromYDn+u3XNT3CAjf0yhXcvJY6iBPQ7aWmsxnavrus2T9ckiFgzFsanULvQChw7sZ2RPZgV1SHcflsNqpD4Wz4QzG6tpqoFG+oAM32cQzm7YhNgACZm7w
Q4g4nLgeECBQGT/4wQ+CpEAFoBaQEjCPsnjx2AiCOQ6ANHEhMsFj7slPWWcqYGJWEt8tUA9gpDyMdenj7W9WnvbwTFKeerxdyhIYF/eHDh3UJ3FP2cPH9tv0hI7nye9QXXpDxt+1HtU7x9LJCdDqWn
pWqjioxCy5sWuNxFbI5+oCRFkua52/KMgnsgEPaZHg7XS+z/brAM7oUX0wPCspMamPhbXLq29p4FEAhOia1YfFLiGYtHNpG4IT1RskRGu2UQDmpwGBHYEagOkQFp3EdjGEZgcUNeOAgeDpC3LxDmay
ecQGDAEwsFIh3ix4fX4ugf7TJperp83K0y59djB6u5SlbmL6wa/28sHLA/smrFA7pYOzOpC8ekWnqJOTUBvbcEatpyQsS4xK4UErAG3VZ3UOom+3vI06QKsMGT7+LV/USakleSil7zPreyFJjZ2MT+
wW2uh8nynol276dXRfZzZzww8JdCN2U9v70BeA54I7XMf5tW9z5crV8A4nY4eECIAQgoLKiDyVMLsgKZAGhPsdID4zCxCAOM5KcI/OJY0OUIczLx2TFjOGdBiDBCL2/OukXb+jLBeAwDAGEAARRjoQ
13Ov31GGwIyhz2EnUH12QFAWacMYINQjDz9kT/zN47ZrShtgi/9XYJDtUJXPoZ6chErxY51P60227+TNsGZG9esDnQyrguGD0vuTgac4tmp3TsmnoY9ndOwuq4O5SVc7Gd6uzG/SyVIbmbxOiA3NWm
HLp3R0f6r1gU/ykRGeT/iyImnOKoMJ/6EAwokPA6gUKcGJHZgIQ2mUdwDEGRvHMMZtCJjjupx31Ee6l/Wxx7GLeICAhKFupBbt8s7ri8tw7+1yT/1+0S6gINAfNu+eeOIJ+8QxHSjepZWSPtatLmqZ
qdVAs8HOYeLNvFdAMMvxVFpekmFAR/Bh2PCs5YrJL+M2KvpedPmcPJXn9CHpeYkRjgUmoKdPPUMaEPo0MCM7IavVS2H8k7IldukL8j6d1kp+rZfT9YCeicRPG3+ogHDx7LM53j6G8DQKcWEWIY6dMT
CiW4ChMKsXY2G8MzBWN9TraiBu09ugvfjiPW3QN8pyATZOhX32s5+xwwd22HBhwfJyUdduv2P1Mi7q+w9ggR1PK+j09MhhHcU/YP0je/Sxjg67KNTKi1a6c0FS4l1tlr2lQ7p8l6H+BO/UxvboJ8Fp
ms6R7dMB3pEDWsnMBlCs6ieKOB1X1SR1QHDmFA2wqYQYHknOQ6grgTgUGMKG0Crj+9//fjAqURluJ4AwCEgHvXPEXD77/H16AM4AH5wPyhnk9fj7OHampstSxsun2+M5bpM6ePZ2KId6xPPKPs1/+v
Snbc+MltfLOjS7dlbifEG2Q3QSKu7QXe6RDmx/N/P6hZjhw1YYPWCDY5ISLUBUBYjVpXNWvf2uNZfflj/iZvJdRhdAxGOOaRt3IZsfkDoa1z7HPsuNPWal5kSQ4OVSOUwIFgCoePjLvtQGG4KZnNgQ
6wdkaLhYSL6QelWrjO9973th+QkgWHoiIVy8kxdgEFxkx4R2RpHuzOSeQFkfpJeJYxjl+ZyJ4UWrrLcLAClHiMv7u7hdbzNul/Js6bObe+zoYfvE0UM2OaLfpFr4F21gndd+haRdo/MkVGjsHv7w1V
ZVq4taZsTq2nfID+/VPsZ+K/Qnfohq6ZatasezJrWR1S/MFJp3RFtWGykJKsGAbEhGGd+kOgHYZU/kh/bK1fEf5LDaYUvaQ1nj5LecYxjU12VsImU3AIIj9jBxM0C8LJf1d77znbDacEAgJRA/BCdw
zAjew0zq9ot8dAKR78GZ4s9eh5fFFiEAPsq5RPL8Xt4Zz3svC5NpO27X83vs+SnDcbInn3zSjh6etalxPsu9JnWeLDOb2A1IP2+4Fbsa9/f+7Nl4HySE3NYlLTdXtNy0on5ne8sD+pxvK8Sz2pp++X
9Rm2Xla9on0c8JtA7IoDY6QvQY2vNGlcmTkleoG6lHLUMLY8f0e0l7ZWBu0U8U6VvU28mPu97QqhAbEEDgVW67rhNAuISID9nyq6uJhHjl1Vftu9/9btjcohLA4KuBjg6nHmAGOh69DmNhKNLF9X8q
e/sR5sJMyrltQruUczXVztzlhnYpG7dLnykfA4GitIX0oG98pshX04cPiJC185YpndPROJ2GqrROQnVp615eJQDVxzrsdq7psz4b0ZmIPdq+1rJTrGzopFV19YLlJRlGBvLhxHX4lE9g+SAhU5SBP8
S3HPssM/SADEz9zoSAgIvgphYB0BR7qTcghiNAqDMOiNfluv7Rj36kEzk6DCJGQVj0DhVuFmAIqwB0FoCgHJtE6OrNAgSkHcCAMcQ9DKWcL2k3K09bLCtpF0Ayjl7tAgjGwVITvwM/xbNv14DVF/+k
n2zQdxIVnYSqdf9NqM36EKfRBlKizOaWvs9AUlTrWoI2EzWbzfJjpjruX5AdI9d1n/YyUBcfEA/6lEN7TsURqSipp8n/aOXmpN3Q9yZ8eoDKYNwcidwIiLYNsQ4IeoOnckiMQIpwDP9FnYvAOoXgLP
OYrZsF8sFUX3HAGBqnIxCpV0gIqBmllQrfUgAQd4YBKrcbepXHJqIsF6CkXQAMmKg7bpt7pBYnyR955JGwutg7rdXK/B9k9Z+W7RAtM3s1eJf3DJV22MvgOH649BuUPBP4IKdf32H098lTy/F7uSrR
FmlpdpdmNiaLhyxDc1px9E//53AoFyBcv65LRmVfCxDYTp0qowWI+LsMancJwSxlYwuPJaen+GQMojNz7xYghM94BgiIENG85+oWyEceysFQ8tEXL9etTLd3lI9tCMrT57hd7gELovP4Y4/Z3/7tk7
Znm467Xf1fCSBCHyPPofdZfSSkhbrXnWYm75ESNS0/AQI7n7iyCeHX/rR/wXcYgIHlpte7oZ5Q4t7bZWIjIfq2CxDZGakLfuLxhl0TIFxCbABEe5UhaRDLqYL0KnsZENW3yl+VPeG/4kK5zQIMQDcz
KJjDRYA4fnUrT343Hr0Mz5SBof6uW1nepdulHIGYsvEz9y4hjsiG+NSnjtv0uPZn5v9ZVv8ZWYQCpJxRCYPod6iqzRFnXFJ/K82ztBK9DG1xz39o0tAZy/AfmygvHsSsvvQm1r9Ar86avMLUW+9L6n
UbRFnRXjuheX1cXJz6tJUzU1IVC4mEkOpAYqIy2oDAu4g6CIDQ518Qpl2ZGoEJ7ZmpZ/Qx0gJRfC+Moa64PmcE/Y/veU4HL+v5vJ6EqD0o0arEy3qdXgfP8T3gcCnHWFlB8U3DsI7CV5delUF5RhtZ
N3S8Xj8WFn49bvN2Q2orC4ztFhwcyf9y08qhvH6gtlsZf5eu0+vydI/D+DUZwxG7/ikZlvssP/6wrWpvg4+tkBDwHpuMo5AbAIGu364jcACC2eXEJ4ZQiPlg3TPbaTXdM+/Jv7MYQCD9GD8gZ7wQqZ
grWbZ6Wd9b6MMb7TM0a5yZFKd7ciCktv4kRHA8OIQSurUIRFUpWgWSdnmfytZWJenyHflUWeCh9jUyhUkdyNG5S22Jr1byYYUBGJjY2GVdAYGe3iYPHYBAxAMKD1TMcwwUT/v3HjNLkRBISGiAr59x
9unU87B+n3pAx+F993Gdhc7qZPTydbbUR+t9CzTNwGElpZ9bRGtLKs/nEGkm9TS140loRa02WoXjqJXfkSKl1ErVfpBua3X+uwUd/1/VF+hr+h8FNM4VrcAWZaxvAAR2AbudzI7xlksaQ8P1ftzux/
EepuBFRErg5wcYAARpyOoKWmBH+QRZNy0TarSh0b65Pyqts65XOc/RK717ww6KIAGriS/Id3f57xIAP6s/FhEdfgiWdPwMDa5MQIC45KskCBFETq9+fEzeA4gACqSEQAGxAigEEkgd2NHKw31rsrdH
32ZH+6addE83zu7exT1Hr+p6l0TwhLVKSwJRA2Nj8hPzv+yMyffS8bEvqMHIQFKAGOyFCS3B3MfA88dRVTh5HRDBuHRJ0QIF4EByBOPZQZFGhFf0EYuZzEAlxNiErf7xm5Xwmfc4+jAm+S0J7oMfAm
MK6eA/WFUSekalOkYlSrAnfAMLYHxcJQagCMtAAQJgYEcAgpqucK935CF43KLvRzZyANBfxoKKwGvLxeEYNAGSgW9p4HNw6cuX0CQz4gPf9jn9LAAqhOUPOhQwsOT8uEsJZ3RQCS3mB2AADhEUonYF
QgskHxlURKoh9KnVb8YCjwEFICfgiJudTT7Ydh4HCcFAKYB/gT0HliPzUiFLrXOOVBREpvI46kKNH7M/bU0NERkbdNGV3LZTuz6Hlx+hP7EkR90zoWE6diF+FqQCqoJ73rlJEADh4wAU6EskBD9cBT
DcKgUUpP//FrpKBRGh1/uPCn3SgHBpj10IEDjmABh476sn+v7/ANN4XwXqG/biAAAAAElFTkSuQmCC
EOF
}

# Try and ping Google
function CheckInternet() {
        if ping -c 1 $GOOGLE >> /dev/null 2>&1; then
        INTERNET="YES"
        else
        INTERNET="NO"
        fi

}

# Carryout Check  JSSConnection
	function checkCurrJamf() {
	curl -L $CURRENT_JAMF_URL/healthCheck.html -o $TEMPFILE1 > /dev/null 2>&1
	READ_TEMPFILE1=$(cat $TEMPFILE1)
}

# Carryout Check JSSConnection
        function checkNewJamf() {
        curl -L $NEW_JAMF_URL/healthCheck.html -o $TEMPFILE2 > /dev/null 2>&1
		READ_TEMPFILE2=$(cat $TEMPFILE2)
}

# Functions
function DecryptString() {
    echo "${1}" | /usr/bin/openssl enc -aes256 -d -a -A -S "${2}" -k "${3}"
}

function DisplayUserPrompt() {
    
# check to see if CocoaDialog is installed and if not trigger the policy to install it
if ! [ -e "$CocoaDialog" ]; then
        logger "Was not able to find CocoaDialog, trying to install"
        jamf policy -trigger CD
        if ! [ -e "$CocoaDialog" ]; then
                logger "Unable to install CocoaDialog"
                exit 1
        fi
fi

# If the OS is 10.13 or greater this is UAMDM and requires pop ups
if [ "${osMinorVersion}" -ge 13 ]; then
    open /System/Library/PreferencePanes/Profiles.prefPane/
    $CocoaDialog msgbox --icon-file "$TMP_IMAGE" --title "$TITLE" --float --text "$HEADER" --informative-text "Unfortunately, your device has been detected as partially enrolled into our system. Please go to System Preferences->Profiles, click on the Device Enrollment profile and click on approve button." --button1 "OK" 2>&1 > /dev/null
fi    
    
}



# To Enroll to the new jamf
function EnrollNewJamf() {

tmp_Logo
jamf createConf -url ${NEW_JAMF_URL} -verifySSLCert always_except_during_enrollment; jamf startSSH; jamf enroll -invitation "$INVITATION" -noPolicy >/dev/null 2>&1
jamf recon
sleep 10
jamf mdm
jamf manage

   
}

# See if the jamf MDM profile is installed
checkMDMProfileInstalled() {
    enrolled=`/usr/bin/profiles -C | /usr/bin/grep "00000000-0000-0000-A000-4A414D460003"`
    if [ "$enrolled" != "" ]; then
    	echo "MDM Profile Present..."
        mdmPresent=1
    else
    	echo "MDM Profile Successfully Removed..."
        mdmPresent=0
        
        # If the Jamf MDM profile does not exist then enroll to the new mdm server
        EnrollNewJamf
        deleteSelfService
    fi
}

# Send the unmanage command via the api
jamfUnmanageDeviceAPI() {
    /usr/bin/curl -s -X POST -H "Content-Type: text/xml" -u ${USERNAME}:${PASSWORD} ${CURRENT_JAMF_URL}/JSSResource/computercommands/command/UnmanageDevice/id/${jamfProCompID}
    sleep 10
    checkMDMProfileInstalled
    counter=0
    until [ "$REQ_JAMF" = "$NEW_JAMF_URL"/ ] && [ "$mdmPresent" = "1" ] || [ "$counter" -gt "9" ]; do
        ((counter++))
        echo "Check ${counter}/10; MDM Profile Present; waiting 10 seconds to re-check..."
        sleep 10
        checkMDMProfileInstalled
    done
}

deleteSelfService() {
rm -r /Applications/"Self Service.app"
jamf policy
}


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# APPLICATION
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# see if there is internet by pinging google
CheckInternet

if [[ $INTERNET != "YES" ]]; then
	echo "No Internet!"
		exit 1

else


	# Check the healthcheck URL to make sure there is a db connection for both servers
	checkCurrJamf
	checkNewJamf

	# This will read the two temporary files.
	
	# If anything other than [] then there is a problem
	if [[ $READ_TEMPFILE1 != "[]" ]] && [[ READ_TEMPFILE2 != "[]" ]]; then
			echo "There is a problem connecting to the DBs"
		exit 1

# if the DB is ok then it will read []
	elif [[ $READ_TEMPFILE1="[]" ]] && [[ $READ_TEMPFILE2="[]" ]]; then
			echo "Connection to the DBs OK"
            
            # Encrypted Username & password we will use for the api. See https://github.com/jamfit/Encrypted-Script-Parameters
            # Encrypt a username and password of an account with full access in both JSS
USERNAME=$(DecryptString $4 'xxxxx' 'xxxx') 
PASSWORD=$(DecryptString $5 'xxxxxx' 'xxxx')

# get the computer id in jamf
jamfProCompID=$( /usr/bin/curl -s -u ${USERNAME}:${PASSWORD} -H "Accept: text/xml" ${CURRENT_JAMF_URL}/JSSResource/computers/serialnumber/${mySerial}/subset/general | /usr/bin/xpath "//computer/general/id/text()" )
echo "The Computer ID is $jamfProCompID"
            
	fi
				## Remove Configuration Profiles
				echo "Removing MDM Profiles ..."
				if [ "${osMinorVersion}" -ge 13 ]; then
					echo "macOS `/usr/bin/sw_vers -productVersion`; attempting removal via jamf binary..."
					/usr/local/bin/jamf removeMdmProfile -verbose
    				sleep 3
    				checkMDMProfileInstalled
    				if [ "$mdmPresent" == "0" ]; then
        				echo "Successfully Removed MDM Profile..."
                        killall "Self Service" > /dev/null 2>&1
                        DisplayUserPrompt
        				echo "MDM Profile Present; attempting removal via API..."
                        jamfUnmanageDeviceAPI
        				if [ "$mdmPresent" != "0" ]; then
            				echo "MDM Profile exists"
        				fi
    				fi
				else
					echo "macOS `/usr/bin/sw_vers -productVersion`; attempting removal via jamf binary..."
					/usr/local/bin/jamf removeMdmProfile -verbose
   					 sleep 3
    				checkMDMProfileInstalled
    				if [ "$mdmPresent" == "0" ]; then
        				echo "Successfully Removed MDM Profile..."
    					else
        				echo "MDM Profile Present; attempting removal via API..."
        				jamfUnmanageDeviceAPI
        				if [ "$mdmPresent" == "0" ]; then
            				echo "Successfully Removed MDM Profile..."
        				else
            				echo "macOS `/usr/bin/sw_vers -productVersion`; attempting force removal..."
        					/bin/mv -v /var/db/ConfigurationProfiles/ /var/db/ConfigurationProfiles-$timestamp
            				checkMDMProfileInstalled
            				if [ "$mdmPresent" != "0" ]; then
                				echo "MDM Profile exists"
            				fi
        				fi
    				fi
				fi
fi

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CLEANUP & EXIT
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

exit 0
