#!/bin/bash

BUILD="1"

# Harware UUID
UUID=$(/usr/sbin/system_profiler SPHardwareDataType | grep "Hardware UUID" | cut -c22-57)

# Get ip address
MY_IP=$(curl -L -s --max-time 10 http://checkip.dyndns.org | egrep -o -m 1 '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}')


TIMEZONE=$(curl -L -s --max-time 10 http://ip-api.com/csv/?fields=timezone,/$MY_IP)

function enableLocationServices() {

# enabling location services this requires a restart because of SIP
/usr/bin/defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -int 1
/usr/bin/defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd.$UUID LocationServicesEnabled -int 1

# configure automatic timezone
/usr/bin/defaults write /Library/Preferences/com.apple.timezone.auto Active -bool YES
/usr/bin/defaults write /private/var/db/timed/Library/Preferences/com.apple.timed.plist TMAutomaticTimeOnlyEnabled -bool YES
/usr/bin/defaults write /private/var/db/timed/Library/Preferences/com.apple.timed.plist TMAutomaticTimeZoneEnabled -bool YES

/usr/sbin/systemsetup -setusingnetworktime on
/usr/sbin/systemsetup -gettimezone
/usr/sbin/systemsetup -getnetworktimeserver
return 0

}


### MAIN ###

echo "Build is $BUILD"

# now set the time
if [[ "$TIMEZONE" != "" ]]; then
			echo "setting timezone to $TIMEZONE"
			systemsetup -settimezone $TIMEZONE
fi

# enable location Services, requires a restart to reflect in the OS due to SIP
enableLocationServices

exit 0
